### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by tonyliang19** [JialuJin/dsci-310-group-6#19]
Please read below feedbacks on things that you could've improve on for future milestones, **NOTE** if these are not fixed, marks will be deducted. If you have any questions on these feedbacks, please feel free to drop-in to my office hour or during lecture time

# Milestone 1 Feedback Group 6

### README.md
- [x] Fails to run, instruction wrong, did not explain to clone the project. **-2**

- [x] Didnt mention the packages explicityly and their versions. **-1**

- [x] Names of Licenses NOT mentioned in the README.md. **-1**

### Analysis

- [x] analysis.ipynb should have a better naming, `<question_analysis.ipynb>`. **-1**

- [x] Missed References in your analysis **-3**

### Dockerfile

- [x] Dockerfile is too simple, the base image is usually not enough to provide required packages (not even the tidyverse image). **-4**

### GitHub Workflow

- [x] Workflow should trigger only when changes made on Dockerfile instead of any modification to your main either through direct push / PR **-1**

### Project File and Directory Structure

- [x] Extra docker_compose.yml, please do not blindly copy and paste, the file you copied is only valid for Tiffany's project, you didn't even change the directory name... Only provide files that actually works **-1**

### GitHub Project/Milestones/Issues

- [x] Missed closing issues that are actually done in your milestone **-1**

- [x] The project board is not reflecting the current status (SHOULD be done at least for milestone 1) of the project to the team. **-1**

### Reproducibility

- [x] Not mached docker image (R-based but you have ipynb file), yet still the Rimage is empty, none of the dependencies you have in the file is within the image, hence environment is not reproducible **-5**

- [x] Not able to reproduce the analysis using the documentation provide in the README.md **-10**
