### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by tonyliang19** [JialuJin/dsci-310-group-6#54]
# Milestone 2 Feedback Group 6

### Code is abstracted to functions with good function design 

- [x] Repeated code of making recipe, workflow, fitting (This could be abstracted to function as well) **-5** 
- [x] Functions do not handle exceptions **-2**

### Functions are well documented And Tests

- [x] Generic script or function scripts are not clear to differentiate, bad documentation, no Roxygen style doc for functions, no informations on parameters **-8**
- [x] None of tests covered cases for wrong input types/right output types (except 1) **-4**
- [x] **Summary_data**, comment mentioned produces one of mean/min/max, but median was the actual **-1**

### Helper data for tests is tractable and reproducible

- [x] No code that reproduces or generates the helper data **-2**

### Dependecies Update

- [x] Unmatched versions of packages listed in your `README.md` **-2**
    + `digest=0.6.31` but actually 0.6.29
    + `readxl=1.4.1` but actually 1.4.0
    + `tidymodels=1.0.0` but actually 0.2.0 (This is more severe)
    + `tidyverse=1.3.2` but actually 1.3.1

### Project file and directory struture organization
- [x] Extra `Rplots.pdf` in the root level of project **-1**
- [x] Extra `bike_share_analysis.ipynb` in the root level of project **-1**

#### GitHub Issue Milestones

- [x] Make sure to close the issue that have **actually done** the task, and not just move this to done in the Project board **-1**

#### Follows GitHub flow version control workflow

- [x] Not completely following GitHub flow version control, please let your groupmate at least review it to approve your changes by merging the PR by themselves and **NOT** by yourself **-1**
    > This is another important way to cross check your work, and remember you're not working alone, you have your teammates by your side!

### Analysis can be run reproducibly using doc in README
- [x] Missed instruction for authentication, i.e. username and password combination from your Docker run command **-1**

- [x] Please be precise in your `Dockerfile`, do not install same package multiple times **-2**

Side notes: 
1. update your analysis'seed or the results with thing you would be learnt in individual-assignment 4. Your `summary` tibble has RMSE of **1338**, while in your discussion, you mentioned **1483**. See below:
![image](https://user-images.githubusercontent.com/83138402/226675838-3f91876e-370f-49b8-9297-9ffc5ca079c1.png)

3. Please decide if you want to do your report in Rstudio only/JupyterLab only/both, then provide its correpondant instructions to reproduce the report
