### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by tonyliang19** [JialuJin/dsci-310-group-6#81]
# Milestone 3 Feedback Group 6

## Project file and directory structure organization

- [ ] Extra `installed_packages` in top-level root directory **-1**
- [ ] Extra `.bash_history`, `README.html` in top-level root directory **-1**

Side Note:

In your `src` directory, `prediction.r` is not having upper case `R` as extension, whereas all other files there do.

## Analysis can be run reproducibly using documentation provided in README

- [x] Inconsistent RMSE from summary and discussion **-1**, since you did not change `Summary` sections's constants to inline R code, for example: 
> Our current model has predition error, ... of about $1483$. 

While in your `Discussion` portion you had $1464$ which is from `r round(predicted_RMSE,digits = 0)`. Please be consistent through your report

## Address Feedback from Milestone 1 and 2

Up to 50 % of Milestone 1 + Milestone 2 points, if feedback and comments are adequately addressed

Total = $15.5 * 2 = 31$ points , for calculation see below: 

### [Milestone 2 Feedback](https://github.com/JialuJin/dsci-310-group-6/issues/54)

- Code abstracted to functions with good function design **50% of 7 = 3.5**
- Functions are well documented and Test **50% of 13 = 6.5**
- Helper data for tests is tractable and reproducible **50% of 2 = 1**
- Dependencies Update **50% of 2 = 1**
- Project file and directory structure organization **50% of 2 = 1**
- GitHub **50% of 2 = 1** 
- Analysis can be run reproducibly using README **50% of 3 = 1.5**

Total = $3.5 + 6.5 + (4 * 1) + 1.5 = 15.5$ points 

### [Milestone 1 Feedback](https://github.com/JialuJin/dsci-310-group-6/issues/19)

- `README.md` **50% of 4 = 2**
- Analysis **50% of 4 = 2**
- Dockerfile **50% of 4 = 2**
- GitHub Workflow **50% of 1 = 0.5**
- Project File and Directory Structure **50% of 1 = 0.5**
- GitHub Project/Milestones/Issues **50% of 2 = 1**
- Reproducibility **50% of 15 = 7.5**

Total = $(3 * 2) + (0.5 * 2) + 1 + 7.5 = 15.5$ points
